#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo $SCRIPT_DIR
rm $SCRIPT_DIR/docs -rf
rm $SCRIPT_DIR/Working\ Data -rf

git submodule update --init
mono ../Dependencies/bin/NaturalDocs/NaturalDocs.exe $SCRIPT_DIR --only-access-levels public protected
