#!/bin/bash

if [[ "darwin" != *"$PLATFORM"* ]]; then
  echo "This platform is not MacOS."
  echo "Use build_natives to build for a supported platform."
  exit
fi

CMAKE_FRAMEWORKS="-lc++ -framework CoreFoundation -framework CoreText -framework CoreGraphics"

FT_SOPATH=$FT_BUILDROOT/libfreetype.6.20.2.dylib
FT_ARTIFACT=libfreetype.dylib

SDL_SOPATH=$SDL_BUILDROOT/libSDL2-2.0.0.dylib
SDL_ARTIFACT=libSDL2.dylib

SDL_GPU_SOPATH=$SDL_GPU_BUILDROOT/SDL_gpu/lib/libSDL2_gpu.dylib
SDL_GPU_ARTIFACT=libSDL2_gpu.dylib

SDL_SOUND_SOPATH=$SDL_SOUND_BUILDROOT/libSDL2_sound.$SDLSOUND_VER.dylib
SDL_SOUND_ARTIFACT=libSDL2_sound.dylib

if [ "$SKIP_FT" -eq "0" ]; then
echo
echo " -- [[ BUILDING FREETYPE ]] -- "
      $CMAKE $CMAKE_FLAGS -B $FT_BUILDROOT $FT_PATH -G "$CMAKE_GENERATOR"                 \
                        -DCMAKE_BUILD_TYPE=$FT_BUILD_TYPE                                 \
                        -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                        -DBUILD_SHARED_LIBS=ON                                            \
                        -DFT_ENABLE_ERROR_STRINGS=ON                                      \
                        -DFT_DISABLE_ZLIB=ON                                              \
                        -DFT_DISABLE_BZIP2=ON                                             \
                        -DFT_DISABLE_BROTLI=ON                                            \
                        -DFT_DISABLE_PNG=ON                                               \
                        -DFT_DISABLE_HARFBUZZ=ON                                          \
                         && cd $FT_BUILDROOT && $MAKE -j$THREADCOUNT                      \
                         && mv $FT_SOPATH $ARTIFACT_DIR/$FT_ARTIFACT                      \
                                                                                          \
    && $CMAKE $CMAKE_FLAGS -B $HB_BUILDROOT $HB_PATH -G "$CMAKE_GENERATOR"                \
                        -DCMAKE_BUILD_TYPE=$HB_BUILD_TYPE                                 \
			                  -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                        -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF                              \
                        -DCMAKE_CXX_FLAGS=-fPIC                                           \
                        -DCMAKE_C_FLAGS=-fPIC                                             \
                        -DHB_BUILD_SUBSET=FALSE                                           \
                        -DHB_HAVE_FREETYPE=TRUE                                           \
                        -DFREETYPE_FOUND=TRUE                                             \
                        -DFREETYPE_INCLUDE_DIRS=$FT_PATH/include                          \
                        -DFREETYPE_LIBRARY=$ARTIFACT_DIR/$FT_ARTIFACT                     \
                         && cd $HB_BUILDROOT && $MAKE -j$THREADCOUNT                      \
                         && mv $HB_ARPATH $ARTIFACT_DIR/$HB_ARTIFACT                      \
                         && rm -rf $FT_BUILDROOT                                          \
                                                                                          \
    && $CMAKE $CMAKE_FLAGS -B $FT_BUILDROOT $FT_PATH -G "$CMAKE_GENERATOR"                \
                        -DCMAKE_BUILD_TYPE=$FT_BUILD_TYPE                                 \
                        -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                        -DCMAKE_SHARED_LINKER_FLAGS="$CMAKE_FRAMEWORKS"                   \
                        -DCMAKE_SKIP_RPATH=OFF                                            \
                        -DBUILD_SHARED_LIBS=ON                                            \
                        -DFT_ENABLE_ERROR_STRINGS=ON                                      \
                        -DFT_DISABLE_ZLIB=ON                                              \
                        -DFT_DISABLE_BZIP2=ON                                             \
                        -DFT_DISABLE_BROTLI=ON                                            \
                        -DFT_DISABLE_PNG=ON                                               \
                        -DFT_DISABLE_HARFBUZZ=OFF                                         \
                        -DFT_REQUIRE_HARFBUZZ=TRUE                                        \
                        -DHarfBuzz_INCLUDE_DIR=$HB_PATH/src                               \
                        -DHarfBuzz_LIBRARY=$ARTIFACT_DIR/$HB_ARTIFACT                     \
                         && cd $FT_BUILDROOT && $MAKE -j$THREADCOUNT                      \
                         && mv $FT_SOPATH $ARTIFACT_DIR/$FT_ARTIFACT
fi

echo
echo " -- [[ BUILDING SDL ]] -- "
   $CMAKE $CMAKE_FLAGS -B $SDL_BUILDROOT $SDL_PATH -G "$CMAKE_GENERATOR"              \
                    -DCMAKE_BUILD_TYPE=$SDL_BUILD_TYPE                                \
                    -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                    -DSDL_STATIC=0                                                    \
                     && cd $SDL_BUILDROOT && $MAKE -j$THREADCOUNT                     \
                     && mv $SDL_SOPATH $ARTIFACT_DIR/$SDL_ARTIFACT                    \
                                                                                      \
&& $CMAKE $CMAKE_FLAGS -B $SDL_GPU_BUILDROOT $SDL_GPU_PATH -G "$CMAKE_GENERATOR"      \
                    -DCMAKE_BUILD_TYPE=$SDL_GPU_BUILD_TYPE                            \
                    -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                    -DSDL2_INCLUDE_DIR=$SDL_PATH/include                              \
                    -DSDL2_LIBRARY=$ARTIFACT_DIR/$SDL_ARTIFACT                        \
                                                                                      \
&& $CMAKE $CMAKE_FLAGS -B $SDL_GPU_BUILDROOT $SDL_GPU_PATH -G "$CMAKE_GENERATOR"      \
                    -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                    -DDISABLE_OPENGL_1_BASE=1                                         \
                    -DDISABLE_OPENGL_1=1                                              \
                    -DDISABLE_OPENGL_2=1                                              \
                    -DBUILD_STATIC=0                                                  \
                    -DBUILD_DEMOS=0                                                   \
                    -DBUILD_FRAMEWORK=0                                               \
                     && cd $SDL_GPU_BUILDROOT && $MAKE -j$THREADCOUNT                 \
                     && mv $SDL_GPU_SOPATH $ARTIFACT_DIR/$SDL_GPU_ARTIFACT            \
                                                                                      \
&& $CMAKE $CMAKE_FLAGS -B $SDL_SOUND_BUILDROOT $SDL_SOUND_PATH -G "$CMAKE_GENERATOR"  \
                    -DCMAKE_BUILD_TYPE=$SDL_SOUND_BUILD_TYPE                          \
                    -DCMAKE_OSX_ARCHITECTURES="arm64"                                 \
                    -DCMAKE_SKIP_RPATH=0                                              \
                    -DSDLSOUND_BUILD_STATIC=0                                         \
                    -DSDLSOUND_BUILD_SHARED=1                                         \
                    -DSDLSOUND_BUILD_TEST=0                                           \
                    -DCMAKE_MODULE_PATH=$CMAKE_SCRIPT_DIR                             \
                    -DSDL2_INCLUDE_DIRS=$SDL_PATH/include                             \
                    -DSDL2_INCLUDE_DIR=$SDL_PATH/include                              \
                    -DSDL2_LIBRARY=$ARTIFACT_DIR/$SDL_ARTIFACT                        \
                    -DSDL2_LIBRARIES=$ARTIFACT_DIR/$SDL_ARTIFACT                      \
                     && cd $SDL_SOUND_BUILDROOT && $MAKE -j$THREADCOUNT               \
                     && mv $SDL_SOUND_SOPATH $ARTIFACT_DIR/$SDL_SOUND_ARTIFACT        \
&& bzip2 $ARTIFACT_DIR/*.dylib                                                        \
