name: Build Windows natives

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
    - uses: Totto16/msys2-install-packages-pinned@v1.0.1
      with:
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc=14
          patch
    - name: Put MSYS2_MinGW64 on PATH
      run: echo "$RUNNER_TEMP/msys64/mingw64/bin" >> $GITHUB_PATH

    - shell: bash
      name: Build
      run: cd Dependencies && ./build_natives --with-ft && cd ..

    - name: Pack artifact
      uses: actions/upload-artifact@v4
      with:
        name: chroma-natives-windows
        path: Dependencies/build_env/artifacts
        if-no-files-found: error
        retention-days: 90
