name: Build macOS natives

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: Symbitic/install-cmake@v0.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        platform: mac

    - name: Build
      run: cd Dependencies && ./build_natives --with-ft && cd ..

    - name: Pack artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: chroma-natives-macos
        path: Dependencies/build_env/artifacts
        if-no-files-found: error
        retention-days: 90
