name: Build Windows natives

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          patch

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "$RUNNER_TEMP/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Build
      run: cd Dependencies && ./build_natives --with-ft && cd ..

    - name: Pack artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: chroma-natives-windows
        path: Dependencies/build_env/artifacts
        if-no-files-found: error
        retention-days: 90
