name: Build macOS natives

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@v4.0.2
      with: 
        cmakeVersion: 3.31.7
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Build
      run: cd Dependencies && ./build_natives --with-ft && cd ..

    - name: Pack artifact
      uses: actions/upload-artifact@v4
      with:
        name: chroma-natives-macos
        path: Dependencies/build_env/artifacts
        if-no-files-found: error
        retention-days: 90
